In [1]:
import numpy as np

In [11]:
myarr=np.array([[2,3,45,5,5,4,]],np.int8)

In [14]:
myarr[0,2]

45

In [15]:
myarr[0,2]=99

In [16]:
myarr

array([[ 2,  3, 99,  5,  5,  4]], dtype=int8)

In [17]:
liar=np.array([[1,2,3],[43,23,34],[21,33,43]])

In [18]:
liar

array([[ 1,  2,  3],
       [43, 23, 34],
       [21, 33, 43]])

In [19]:
liar.shape

(3, 3)

In [20]:
liar.size

9

In [21]:
liar.dtype

dtype('int32')

In [22]:
dict=np.array({23,44,55})

In [23]:
dict

array({44, 23, 55}, dtype=object)

In [24]:
zerps=np.zeros((2,5))

In [25]:
zerps

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
rng=np.arange(18)

In [30]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [31]:
rng.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [43]:
rng.sum(axis=0)

153

In [32]:
rng.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [33]:
lspace=np.linspace(1,5,4)

In [34]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [35]:
emp=np.empty((4,6))

In [36]:
emp

array([[9.77997360e-312, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 7.56587583e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        1.05132385e-153, 1.05161519e-153, 1.05190653e-153],
       [1.05219787e-153, 1.05248921e-153, 1.05133352e-153,
        1.05162486e-153, 1.05191620e-153, 6.01391519e-154],
       [1.94373161e-109, 4.90900643e+252, 1.94918511e-153,
        6.32672800e+180, 4.74483502e+170, 1.97229332e-062]])

In [38]:
emp_like=np.empty_like(lspace)

In [39]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [40]:
ide=np.identity(45)

In [41]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [42]:
rng.sum(axis=0)

153

In [44]:
liar.sum(axis=0)

array([65, 58, 80])

In [46]:
liar.sum(axis=1)

array([  6, 100,  97])

In [47]:
liar.T

array([[ 1, 43, 21],
       [ 2, 23, 33],
       [ 3, 34, 43]])

In [49]:
liar.flat

In [53]:
for item in liar.flat:
    print(item)

1
2
3
43
23
34
21
33
43


In [54]:
liar.ndim

2

In [56]:
liar.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [59]:
liar.size

9

In [60]:
liar.nbytes

36

In [62]:
liar.argmax()

3

In [63]:
liar.argmin()

0

In [64]:
rng.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17], dtype=int64)

In [65]:
liar.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [66]:
dict.argsort()

array([0], dtype=int64)

In [67]:
myarr.argsort()

array([[0, 1, 5, 3, 4, 2]], dtype=int64)